# Generated by Django 2.1.5 on 2019-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.DecimalField(decimal_places=4, max_digits=20)),
                ('column_2', models.DecimalField(decimal_places=4, max_digits=20)),
                ('column_3', models.DecimalField(decimal_places=4, max_digits=20)),
                ('column_4', models.DecimalField(decimal_places=4, max_digits=20)),
                ('column_5', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
