# Generated by Django 2.1.5 on 2019-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
